ALTER TABLE users
    ALTER user_id ADD GENERATED BY DEFAULT;

-- Check to see if the sequences need updating.
SELECT
    last_value, (SELECT MAX (id) FROM storage_bins) as max_id
FROM storage_bins_id_seq;

-- After a bulk import the table sequences will need to be reset to the max value.
-- These need to be run one at a time for some reason.
SELECT setval('manufacturers_manufacturer_id_seq', max(manufacturer_id)) FROM manufacturers;
SELECT setval('order_parts_order_part_id_seq', max(order_part_id)) FROM order_parts;
SELECT setval('orders_order_id_seq', max(order_id)) FROM orders;
SELECT setval('part_types_part_type_id_seq', max(part_type_id)) FROM part_types;
SELECT setval('parts_part_id_seq', max(part_id)) FROM parts;
SELECT setval('project_parts_project_part_id_seq', max(project_part_id)) FROM project_parts;
SELECT setval('projects_project_id_seq', max(project_id)) FROM projects;
SELECT setval('storage_bins_storage_bin_id_seq', max(storage_bin_id)) FROM storage_bins;
SELECT setval('suppliers_supplier_id_seq', max(supplier_id)) FROM suppliers;
SELECT setval('user_parts_user_part_id_seq', max(user_part_id)) FROM user_parts;
SELECT setval('users_user_id_seq', max(user_id)) FROM users;


-- Drop Tables
DROP TABLE IF EXISTS project_parts;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS user_parts;
DROP TABLE IF EXISTS storage_bins;
DROP TABLE IF EXISTS order_parts;
DROP TABLE IF EXISTS parts;
DROP TABLE IF EXISTS part_types;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS manufacturers;
DROP TABLE IF EXISTS suppliers;
DROP TABLE IF EXISTS users;

-- Create Tables
CREATE TABLE users
(
	user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_name VARCHAR(24) NOT NULL,
	email VARCHAR(60) NOT NULL,
	mouser_api_key_orders VARCHAR(128),
	mouser_api_key_search VARCHAR(128)
);

CREATE TABLE suppliers
(
	supplier_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	supplier_name VARCHAR(60) NOT NULL,
	base_url VARCHAR(255) NOT NULL
);

CREATE TABLE manufacturers
(
	manufacturer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	manufacturer_name VARCHAR(60) NOT NULL,
	description VARCHAR(255),
	manufacturer_url VARCHAR(255),
	aliases VARCHAR(255)
);

DROP TYPE IF EXISTS order_status;
CREATE TYPE order_status AS ENUM ('created', 'shipped', 'imported', 'complete');

CREATE TABLE orders
(
	order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id BIGINT NOT NULL REFERENCES users (user_id),
	supplier_id BIGINT NOT NULL REFERENCES suppliers (supplier_id),
	order_date DATE NOT NULL,
	order_number VARCHAR(24) NOT NULL,
	currency_code CHAR(3) NOT NULL,
	status order_status NOT NULL
);

CREATE TABLE part_types
(
	part_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	parent_id INT NOT NULL,
	short_name VARCHAR(60) NOT NULL,
	long_name VARCHAR(120) NOT NULL,
	mouser_url VARCHAR(255) NOT NULL
);

CREATE TABLE parts
(
	part_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	part_type_id BIGINT REFERENCES part_types (part_type_id),
	part_number VARCHAR(32) NOT NULL,
	series VARCHAR(32),
	description VARCHAR(255),
    manufacturer_id BIGINT NOT NULL REFERENCES manufacturers (manufacturer_id),
	product_url VARCHAR(255),
	image_url VARCHAR(255),
	datasheet_url VARCHAR(255)
);

CREATE TABLE storage_bins
(
	storage_bin_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id BIGINT NOT NULL REFERENCES users (user_id),
	short_name VARCHAR(60) NOT NULL,
	long_name VARCHAR(120) NOT NULL,
	description VARCHAR(255),
	location VARCHAR(80),
	max_column INT,
	max_row INT
);

CREATE TABLE projects
(
	project_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id BIGINT NOT NULL REFERENCES users (user_id),
	project_name VARCHAR(60) NOT NULL,
	description VARCHAR(255) NOT NULL,
	notes TEXT
);

CREATE TABLE project_parts
(
	project_part_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	project_id BIGINT NOT NULL REFERENCES projects (project_id),
	part_id BIGINT NOT NULL REFERENCES parts (part_id),
	quantity INT NOT NULL
);

CREATE TABLE user_parts
(
	user_part_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id BIGINT NOT NULL REFERENCES users (user_id),
	part_id BIGINT NOT NULL REFERENCES parts (part_id),
	storage_bins_id BIGINT NOT NULL REFERENCES storage_bins (storage_bin_id),
	columnNumber INT NOT NULL,
	rowNumber INT NOT NULL,
	quantity INT NOT NULL
);

CREATE TABLE order_parts
(
	order_part_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	order_id BIGINT NOT NULL REFERENCES orders (order_id),
	part_id BIGINT NOT NULL REFERENCES parts (part_id),
	quantity INT NOT NULL,
	unit_price REAL NOT NULL,
	supplier_part_number VARCHAR(32) NOT NULL,
	manufacturer_part_number VARCHAR(32) NOT NULL,
	manufacturer_name VARCHAR(60) NOT NULL,
	description VARCHAR(255)
);
