// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/main": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/concerts": {
    params: {};
  };
  "/concerts/:city": {
    params: {
      "city": string;
    };
  };
  "/concerts/trending": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/main" | "/about" | "/admin" | "/login" | "/register" | "/concerts" | "/concerts/:city" | "/concerts/trending";
  };
  "./src/pages/Main.tsx": {
    id: "src/pages/Main";
    page: "/main";
  };
  "./src/pages/About.tsx": {
    id: "src/pages/About";
    page: "/about";
  };
  "./src/pages/Admin.tsx": {
    id: "src/pages/Admin";
    page: "/admin";
  };
  "./auth/layout.tsx": {
    id: "auth/layout";
    page: "/login" | "/register" | "/concerts" | "/concerts/:city" | "/concerts/trending";
  };
  "./auth/login.tsx": {
    id: "auth/login";
    page: "/login";
  };
  "./auth/register.tsx": {
    id: "auth/register";
    page: "/register";
  };
  "./concerts/home.tsx": {
    id: "concerts/home";
    page: "/concerts";
  };
  "./concerts/city.tsx": {
    id: "concerts/city";
    page: "/concerts/:city";
  };
  "./concerts/trending.tsx": {
    id: "concerts/trending";
    page: "/concerts/trending";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "src/pages/Main": typeof import("./app/./src/pages/Main.tsx");
  "src/pages/About": typeof import("./app/./src/pages/About.tsx");
  "src/pages/Admin": typeof import("./app/./src/pages/Admin.tsx");
  "auth/layout": typeof import("./app/./auth/layout.tsx");
  "auth/login": typeof import("./app/./auth/login.tsx");
  "auth/register": typeof import("./app/./auth/register.tsx");
  "concerts/home": typeof import("./app/./concerts/home.tsx");
  "concerts/city": typeof import("./app/./concerts/city.tsx");
  "concerts/trending": typeof import("./app/./concerts/trending.tsx");
};