// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/main": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/admin": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/main" | "/about" | "/admin";
  };
  "./pages/Main.tsx": {
    id: "pages/Main";
    page: "/main";
  };
  "./pages/About.tsx": {
    id: "pages/About";
    page: "/about";
  };
  "./pages/Admin.tsx": {
    id: "pages/Admin";
    page: "/admin";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "pages/Main": typeof import("./app/./pages/Main.tsx");
  "pages/About": typeof import("./app/./pages/About.tsx");
  "pages/Admin": typeof import("./app/./pages/Admin.tsx");
};