/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StorageBinsRouteImport } from './routes/storage-bins'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminPartsIndexRouteImport } from './routes/admin/parts/index'
import { Route as AdminPartTypesIndexRouteImport } from './routes/admin/part-types/index'
import { Route as AdminManufacturersIndexRouteImport } from './routes/admin/manufacturers/index'
import { Route as AdminManufacturersCreateRouteImport } from './routes/admin/manufacturers/create'
import { Route as AdminManufacturersManufacturerIdViewRouteImport } from './routes/admin/manufacturers/$manufacturerId.view'
import { Route as AdminManufacturersManufacturerIdEditRouteImport } from './routes/admin/manufacturers/$manufacturerId.edit'
import { Route as AdminManufacturersManufacturerIdDeleteRouteImport } from './routes/admin/manufacturers/$manufacturerId.delete'

const StorageBinsRoute = StorageBinsRouteImport.update({
  id: '/storage-bins',
  path: '/storage-bins',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPartsIndexRoute = AdminPartsIndexRouteImport.update({
  id: '/admin/parts/',
  path: '/admin/parts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPartTypesIndexRoute = AdminPartTypesIndexRouteImport.update({
  id: '/admin/part-types/',
  path: '/admin/part-types/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManufacturersIndexRoute = AdminManufacturersIndexRouteImport.update({
  id: '/admin/manufacturers/',
  path: '/admin/manufacturers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManufacturersCreateRoute =
  AdminManufacturersCreateRouteImport.update({
    id: '/admin/manufacturers/create',
    path: '/admin/manufacturers/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminManufacturersManufacturerIdViewRoute =
  AdminManufacturersManufacturerIdViewRouteImport.update({
    id: '/admin/manufacturers/$manufacturerId/view',
    path: '/admin/manufacturers/$manufacturerId/view',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminManufacturersManufacturerIdEditRoute =
  AdminManufacturersManufacturerIdEditRouteImport.update({
    id: '/admin/manufacturers/$manufacturerId/edit',
    path: '/admin/manufacturers/$manufacturerId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminManufacturersManufacturerIdDeleteRoute =
  AdminManufacturersManufacturerIdDeleteRouteImport.update({
    id: '/admin/manufacturers/$manufacturerId/delete',
    path: '/admin/manufacturers/$manufacturerId/delete',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/orders': typeof OrdersRoute
  '/parts': typeof PartsRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/storage-bins': typeof StorageBinsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/manufacturers/create': typeof AdminManufacturersCreateRoute
  '/admin/manufacturers/': typeof AdminManufacturersIndexRoute
  '/admin/part-types/': typeof AdminPartTypesIndexRoute
  '/admin/parts/': typeof AdminPartsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/manufacturers/$manufacturerId/delete': typeof AdminManufacturersManufacturerIdDeleteRoute
  '/admin/manufacturers/$manufacturerId/edit': typeof AdminManufacturersManufacturerIdEditRoute
  '/admin/manufacturers/$manufacturerId/view': typeof AdminManufacturersManufacturerIdViewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/orders': typeof OrdersRoute
  '/parts': typeof PartsRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/storage-bins': typeof StorageBinsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/manufacturers/create': typeof AdminManufacturersCreateRoute
  '/admin/manufacturers': typeof AdminManufacturersIndexRoute
  '/admin/part-types': typeof AdminPartTypesIndexRoute
  '/admin/parts': typeof AdminPartsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/manufacturers/$manufacturerId/delete': typeof AdminManufacturersManufacturerIdDeleteRoute
  '/admin/manufacturers/$manufacturerId/edit': typeof AdminManufacturersManufacturerIdEditRoute
  '/admin/manufacturers/$manufacturerId/view': typeof AdminManufacturersManufacturerIdViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/orders': typeof OrdersRoute
  '/parts': typeof PartsRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/storage-bins': typeof StorageBinsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/manufacturers/create': typeof AdminManufacturersCreateRoute
  '/admin/manufacturers/': typeof AdminManufacturersIndexRoute
  '/admin/part-types/': typeof AdminPartTypesIndexRoute
  '/admin/parts/': typeof AdminPartsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/manufacturers/$manufacturerId/delete': typeof AdminManufacturersManufacturerIdDeleteRoute
  '/admin/manufacturers/$manufacturerId/edit': typeof AdminManufacturersManufacturerIdEditRoute
  '/admin/manufacturers/$manufacturerId/view': typeof AdminManufacturersManufacturerIdViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/orders'
    | '/parts'
    | '/profile'
    | '/projects'
    | '/storage-bins'
    | '/admin/settings'
    | '/admin/'
    | '/admin/manufacturers/create'
    | '/admin/manufacturers/'
    | '/admin/part-types/'
    | '/admin/parts/'
    | '/admin/users/'
    | '/admin/manufacturers/$manufacturerId/delete'
    | '/admin/manufacturers/$manufacturerId/edit'
    | '/admin/manufacturers/$manufacturerId/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/orders'
    | '/parts'
    | '/profile'
    | '/projects'
    | '/storage-bins'
    | '/admin/settings'
    | '/admin'
    | '/admin/manufacturers/create'
    | '/admin/manufacturers'
    | '/admin/part-types'
    | '/admin/parts'
    | '/admin/users'
    | '/admin/manufacturers/$manufacturerId/delete'
    | '/admin/manufacturers/$manufacturerId/edit'
    | '/admin/manufacturers/$manufacturerId/view'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/orders'
    | '/parts'
    | '/profile'
    | '/projects'
    | '/storage-bins'
    | '/admin/settings'
    | '/admin/'
    | '/admin/manufacturers/create'
    | '/admin/manufacturers/'
    | '/admin/part-types/'
    | '/admin/parts/'
    | '/admin/users/'
    | '/admin/manufacturers/$manufacturerId/delete'
    | '/admin/manufacturers/$manufacturerId/edit'
    | '/admin/manufacturers/$manufacturerId/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  OrdersRoute: typeof OrdersRoute
  PartsRoute: typeof PartsRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  StorageBinsRoute: typeof StorageBinsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminManufacturersCreateRoute: typeof AdminManufacturersCreateRoute
  AdminManufacturersIndexRoute: typeof AdminManufacturersIndexRoute
  AdminPartTypesIndexRoute: typeof AdminPartTypesIndexRoute
  AdminPartsIndexRoute: typeof AdminPartsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminManufacturersManufacturerIdDeleteRoute: typeof AdminManufacturersManufacturerIdDeleteRoute
  AdminManufacturersManufacturerIdEditRoute: typeof AdminManufacturersManufacturerIdEditRoute
  AdminManufacturersManufacturerIdViewRoute: typeof AdminManufacturersManufacturerIdViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/storage-bins': {
      id: '/storage-bins'
      path: '/storage-bins'
      fullPath: '/storage-bins'
      preLoaderRoute: typeof StorageBinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/parts/': {
      id: '/admin/parts/'
      path: '/admin/parts'
      fullPath: '/admin/parts/'
      preLoaderRoute: typeof AdminPartsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/part-types/': {
      id: '/admin/part-types/'
      path: '/admin/part-types'
      fullPath: '/admin/part-types/'
      preLoaderRoute: typeof AdminPartTypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manufacturers/': {
      id: '/admin/manufacturers/'
      path: '/admin/manufacturers'
      fullPath: '/admin/manufacturers/'
      preLoaderRoute: typeof AdminManufacturersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manufacturers/create': {
      id: '/admin/manufacturers/create'
      path: '/admin/manufacturers/create'
      fullPath: '/admin/manufacturers/create'
      preLoaderRoute: typeof AdminManufacturersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manufacturers/$manufacturerId/view': {
      id: '/admin/manufacturers/$manufacturerId/view'
      path: '/admin/manufacturers/$manufacturerId/view'
      fullPath: '/admin/manufacturers/$manufacturerId/view'
      preLoaderRoute: typeof AdminManufacturersManufacturerIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manufacturers/$manufacturerId/edit': {
      id: '/admin/manufacturers/$manufacturerId/edit'
      path: '/admin/manufacturers/$manufacturerId/edit'
      fullPath: '/admin/manufacturers/$manufacturerId/edit'
      preLoaderRoute: typeof AdminManufacturersManufacturerIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manufacturers/$manufacturerId/delete': {
      id: '/admin/manufacturers/$manufacturerId/delete'
      path: '/admin/manufacturers/$manufacturerId/delete'
      fullPath: '/admin/manufacturers/$manufacturerId/delete'
      preLoaderRoute: typeof AdminManufacturersManufacturerIdDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  OrdersRoute: OrdersRoute,
  PartsRoute: PartsRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  StorageBinsRoute: StorageBinsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminManufacturersCreateRoute: AdminManufacturersCreateRoute,
  AdminManufacturersIndexRoute: AdminManufacturersIndexRoute,
  AdminPartTypesIndexRoute: AdminPartTypesIndexRoute,
  AdminPartsIndexRoute: AdminPartsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminManufacturersManufacturerIdDeleteRoute:
    AdminManufacturersManufacturerIdDeleteRoute,
  AdminManufacturersManufacturerIdEditRoute:
    AdminManufacturersManufacturerIdEditRoute,
  AdminManufacturersManufacturerIdViewRoute:
    AdminManufacturersManufacturerIdViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
