/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StorageBinsRouteImport } from './routes/storage-bins'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminPartsRouteImport } from './routes/admin/parts'
import { Route as AdminPartTypesRouteImport } from './routes/admin/part-types'
import { Route as AdminManufacturersListRouteImport } from './routes/admin/manufacturers/list'
import { Route as AdminManufacturersCreateRouteImport } from './routes/admin/manufacturers/create'
import { Route as AdminManufacturersViewManufacturerIdRouteImport } from './routes/admin/manufacturers/view.$manufacturerId'
import { Route as AdminManufacturersEditManufacturerIdRouteImport } from './routes/admin/manufacturers/edit.$manufacturerId'
import { Route as AdminManufacturersDeleteManufacturerIdRouteImport } from './routes/admin/manufacturers/delete.$manufacturerId'

const StorageBinsRoute = StorageBinsRouteImport.update({
  id: '/storage-bins',
  path: '/storage-bins',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPartsRoute = AdminPartsRouteImport.update({
  id: '/admin/parts',
  path: '/admin/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPartTypesRoute = AdminPartTypesRouteImport.update({
  id: '/admin/part-types',
  path: '/admin/part-types',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManufacturersListRoute = AdminManufacturersListRouteImport.update({
  id: '/admin/manufacturers/list',
  path: '/admin/manufacturers/list',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManufacturersCreateRoute =
  AdminManufacturersCreateRouteImport.update({
    id: '/admin/manufacturers/create',
    path: '/admin/manufacturers/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminManufacturersViewManufacturerIdRoute =
  AdminManufacturersViewManufacturerIdRouteImport.update({
    id: '/admin/manufacturers/view/$manufacturerId',
    path: '/admin/manufacturers/view/$manufacturerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminManufacturersEditManufacturerIdRoute =
  AdminManufacturersEditManufacturerIdRouteImport.update({
    id: '/admin/manufacturers/edit/$manufacturerId',
    path: '/admin/manufacturers/edit/$manufacturerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminManufacturersDeleteManufacturerIdRoute =
  AdminManufacturersDeleteManufacturerIdRouteImport.update({
    id: '/admin/manufacturers/delete/$manufacturerId',
    path: '/admin/manufacturers/delete/$manufacturerId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/orders': typeof OrdersRoute
  '/parts': typeof PartsRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/storage-bins': typeof StorageBinsRoute
  '/admin/part-types': typeof AdminPartTypesRoute
  '/admin/parts': typeof AdminPartsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/manufacturers/create': typeof AdminManufacturersCreateRoute
  '/admin/manufacturers/list': typeof AdminManufacturersListRoute
  '/admin/manufacturers/delete/$manufacturerId': typeof AdminManufacturersDeleteManufacturerIdRoute
  '/admin/manufacturers/edit/$manufacturerId': typeof AdminManufacturersEditManufacturerIdRoute
  '/admin/manufacturers/view/$manufacturerId': typeof AdminManufacturersViewManufacturerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/orders': typeof OrdersRoute
  '/parts': typeof PartsRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/storage-bins': typeof StorageBinsRoute
  '/admin/part-types': typeof AdminPartTypesRoute
  '/admin/parts': typeof AdminPartsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/admin/manufacturers/create': typeof AdminManufacturersCreateRoute
  '/admin/manufacturers/list': typeof AdminManufacturersListRoute
  '/admin/manufacturers/delete/$manufacturerId': typeof AdminManufacturersDeleteManufacturerIdRoute
  '/admin/manufacturers/edit/$manufacturerId': typeof AdminManufacturersEditManufacturerIdRoute
  '/admin/manufacturers/view/$manufacturerId': typeof AdminManufacturersViewManufacturerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/orders': typeof OrdersRoute
  '/parts': typeof PartsRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/storage-bins': typeof StorageBinsRoute
  '/admin/part-types': typeof AdminPartTypesRoute
  '/admin/parts': typeof AdminPartsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/manufacturers/create': typeof AdminManufacturersCreateRoute
  '/admin/manufacturers/list': typeof AdminManufacturersListRoute
  '/admin/manufacturers/delete/$manufacturerId': typeof AdminManufacturersDeleteManufacturerIdRoute
  '/admin/manufacturers/edit/$manufacturerId': typeof AdminManufacturersEditManufacturerIdRoute
  '/admin/manufacturers/view/$manufacturerId': typeof AdminManufacturersViewManufacturerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/orders'
    | '/parts'
    | '/profile'
    | '/projects'
    | '/storage-bins'
    | '/admin/part-types'
    | '/admin/parts'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
    | '/admin/manufacturers/create'
    | '/admin/manufacturers/list'
    | '/admin/manufacturers/delete/$manufacturerId'
    | '/admin/manufacturers/edit/$manufacturerId'
    | '/admin/manufacturers/view/$manufacturerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/orders'
    | '/parts'
    | '/profile'
    | '/projects'
    | '/storage-bins'
    | '/admin/part-types'
    | '/admin/parts'
    | '/admin/settings'
    | '/admin/users'
    | '/admin'
    | '/admin/manufacturers/create'
    | '/admin/manufacturers/list'
    | '/admin/manufacturers/delete/$manufacturerId'
    | '/admin/manufacturers/edit/$manufacturerId'
    | '/admin/manufacturers/view/$manufacturerId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/orders'
    | '/parts'
    | '/profile'
    | '/projects'
    | '/storage-bins'
    | '/admin/part-types'
    | '/admin/parts'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
    | '/admin/manufacturers/create'
    | '/admin/manufacturers/list'
    | '/admin/manufacturers/delete/$manufacturerId'
    | '/admin/manufacturers/edit/$manufacturerId'
    | '/admin/manufacturers/view/$manufacturerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  OrdersRoute: typeof OrdersRoute
  PartsRoute: typeof PartsRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  StorageBinsRoute: typeof StorageBinsRoute
  AdminPartTypesRoute: typeof AdminPartTypesRoute
  AdminPartsRoute: typeof AdminPartsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminManufacturersCreateRoute: typeof AdminManufacturersCreateRoute
  AdminManufacturersListRoute: typeof AdminManufacturersListRoute
  AdminManufacturersDeleteManufacturerIdRoute: typeof AdminManufacturersDeleteManufacturerIdRoute
  AdminManufacturersEditManufacturerIdRoute: typeof AdminManufacturersEditManufacturerIdRoute
  AdminManufacturersViewManufacturerIdRoute: typeof AdminManufacturersViewManufacturerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/storage-bins': {
      id: '/storage-bins'
      path: '/storage-bins'
      fullPath: '/storage-bins'
      preLoaderRoute: typeof StorageBinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/parts': {
      id: '/admin/parts'
      path: '/admin/parts'
      fullPath: '/admin/parts'
      preLoaderRoute: typeof AdminPartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/part-types': {
      id: '/admin/part-types'
      path: '/admin/part-types'
      fullPath: '/admin/part-types'
      preLoaderRoute: typeof AdminPartTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manufacturers/list': {
      id: '/admin/manufacturers/list'
      path: '/admin/manufacturers/list'
      fullPath: '/admin/manufacturers/list'
      preLoaderRoute: typeof AdminManufacturersListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manufacturers/create': {
      id: '/admin/manufacturers/create'
      path: '/admin/manufacturers/create'
      fullPath: '/admin/manufacturers/create'
      preLoaderRoute: typeof AdminManufacturersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manufacturers/view/$manufacturerId': {
      id: '/admin/manufacturers/view/$manufacturerId'
      path: '/admin/manufacturers/view/$manufacturerId'
      fullPath: '/admin/manufacturers/view/$manufacturerId'
      preLoaderRoute: typeof AdminManufacturersViewManufacturerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manufacturers/edit/$manufacturerId': {
      id: '/admin/manufacturers/edit/$manufacturerId'
      path: '/admin/manufacturers/edit/$manufacturerId'
      fullPath: '/admin/manufacturers/edit/$manufacturerId'
      preLoaderRoute: typeof AdminManufacturersEditManufacturerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manufacturers/delete/$manufacturerId': {
      id: '/admin/manufacturers/delete/$manufacturerId'
      path: '/admin/manufacturers/delete/$manufacturerId'
      fullPath: '/admin/manufacturers/delete/$manufacturerId'
      preLoaderRoute: typeof AdminManufacturersDeleteManufacturerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  OrdersRoute: OrdersRoute,
  PartsRoute: PartsRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  StorageBinsRoute: StorageBinsRoute,
  AdminPartTypesRoute: AdminPartTypesRoute,
  AdminPartsRoute: AdminPartsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminManufacturersCreateRoute: AdminManufacturersCreateRoute,
  AdminManufacturersListRoute: AdminManufacturersListRoute,
  AdminManufacturersDeleteManufacturerIdRoute:
    AdminManufacturersDeleteManufacturerIdRoute,
  AdminManufacturersEditManufacturerIdRoute:
    AdminManufacturersEditManufacturerIdRoute,
  AdminManufacturersViewManufacturerIdRoute:
    AdminManufacturersViewManufacturerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
